In [1]:
#getting and Knowing Data

In [4]:
!pip install pandas numpy

Requirement already satisfied: pandas in D:\Miniconda\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in D:\Miniconda\Lib\site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Miniconda\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Miniconda\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in D:\Miniconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('chipotle.tsv',sep="\t")

In [8]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [9]:
#Step 2 Dataset Overview

In [10]:
df.shape

(4622, 5)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [13]:
# print all columns ' name
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [14]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [18]:
df.describe(include = "all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [19]:
##loc vs iloc

In [20]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [30]:
df.loc[
    (df.quantity == 2) & (df.item_name == "Nantucket Nectar"),
    ['order_id', 'quantity', 'item_name']
]

      order_id  quantity         item_name
601        247         2  Nantucket Nectar
2379       947         2  Nantucket Nectar

In [38]:
df.iloc[10]
#type(df.iloc[[10]])

order_id                                5
quantity                                1
item_name             Chips and Guacamole
choice_description                    NaN
item_price                         $4.45
Name: 10, dtype: object

In [40]:
df.iloc[3:11]

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45

In [45]:
x=df.iloc[3:5, :-1]
y=df.iloc[3:5,-1]
print(x)
print()
print(y)

   order_id  quantity                              item_name  \
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description
3                                                NaN
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...

3     $2.39
4    $16.98
Name: item_price, dtype: str

In [46]:
#Data Manipulation

In [51]:
df.item_price.dtype

In [60]:
df.item_price = df.item_price.apply(
    lambda x : float(x.replace('$',''))
)

In [61]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [69]:
df['total_price'] = df.quantity * df.item_price

In [70]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [72]:
# tổng
revenue = df.total_price.sum()
print(revenue)

39237.02

In [81]:
c=df.groupby("item_name")["quantity"].sum()
c.sort_values(ascending = False).head(5)

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [84]:
#unique Value
df.item_name.value_counts().count()

np.int64(50)

In [85]:
df.item_name.unique()

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos',
                    'Chicken Soft Tacos',
                       'Chicken Burrito',
                           'Canned Soda',
                      'Barbacoa Burrito',
                      'Carnitas Burrito',
                         'Carnitas Bowl',
                         'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
                         'Barbacoa Bowl',
                                 'Chips',
                    'Chicken Salad Bowl',
                            'Steak Bowl',
                   'Barbacoa Soft Tacos',
                        'Veggie Burrito',
                           'Veggie Bowl',
                    'Steak Crispy Tacos',
   'Chips and Tomatillo Red Chili Salsa',
                 'Barbacoa Crispy Tacos',
                     'Veggie Salad Bowl',
    'Chips and Roasted Chili-Corn Salsa',
    'Chips and Roasted Chili Corn Salsa',
                   'Carnitas Soft Tacos',
                         'Chicken Salad',
                     'Canned Soft Drink',
                      'Steak Salad Bowl',
                     '6 Pack Soft Drink',
   'Chips and Tomatillo-Red Chili Salsa',
                                  'Bowl',
                               'Burrito',
                          'Crispy Tacos',
                 'Carnitas Crispy Tacos',
                           'Steak Salad',
     'Chips and Mild Fresh Tomato Salsa',
                     'Veggie Soft Tacos',
                   'Carnitas Salad Bowl',
                   'Barbacoa Salad Bowl',
                                 'Salad',
                   'Veggie Crispy Tacos',
                          'Veggie Salad',
                        'Carnitas Salad']
Length: 50, dtype: str

In [86]:
#Bài 1 — xem dữ liệu
#Hiển thị 10 dòng đầu của dataframe
df.head(10)

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [91]:
'''Bài 2 — thông tin dataset

In:

số dòng và cột
tên các cột
kiểu dữ liệu từng cột'''
df.shape

(4622, 6)

In [92]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description', 'item_price',
       'total_price'],
      dtype='str')

In [93]:
df.dtypes

order_id                int64
quantity                int64
item_name                 str
choice_description        str
item_price            float64
total_price           float64
dtype: object

In [98]:
'''Bài 3 — thống kê quantity

Tính:

mean
max
min'''
df.quantity.describe()

count    4622.000000
mean        1.075725
std         0.410186
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max        15.000000
Name: quantity, dtype: float64

In [107]:
#Bài 4 — lọc món Chicken Bowl
df.loc[df.item_name == "Chicken Bowl"]

,order_id,quantity,item_name,choice_description,item_price,total_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75,8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49,8.49
...,...,...,...,...,...,...
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25,11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75,8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75,8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75,8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75

In [108]:
#Bài 5 — quantity > 1df.loc[df.quantity >1]
df.loc[df.quantity >1]

,order_id,quantity,item_name,choice_description,item_price,total_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
18,9,2,Canned Soda,[Sprite],2.18,4.36
51,23,2,Canned Soda,[Mountain Dew],2.18,4.36
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50,45.00
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98,35.96
...,...,...,...,...,...,...
4491,1786,4,Canned Soft Drink,[Sprite],5.00,20.00
4499,1789,2,Canned Soft Drink,[Coke],2.50,5.00
4560,1812,2,Canned Soft Drink,[Coke],2.50,5.00
4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",17.50,35.00
4582,1822,2,Bottled Water,NaN,3.00,6.00

In [111]:
#Bài 6 — tìm số lần bán của từng món
df.item_name.value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Chips                                    211
Steak Bowl                               211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Steak Salad                                4
Bowl                                       2
Crispy Tacos                               2
Salad                                      2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

In [113]:
df.total_price=df.quantity * df.item_price
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [114]:
df.total_price.sum()

np.float64(39237.02)

In [116]:
df.sort_values(by="item_price",ascending=False)

,order_id,quantity,item_name,choice_description,item_price,total_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,663.75
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25,105.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00,140.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00,140.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75,101.25
...,...,...,...,...,...,...
1057,435,1,Canned Soda,[Mountain Dew],1.09,1.09
117,51,1,Canned Soda,[Diet Dr. Pepper],1.09,1.09
2562,1014,1,Canned Soda,[Coca Cola],1.09,1.09
2544,1009,1,Canned Soda,[Diet Coke],1.09,1.09
2545,1009,1,Bottled Water,NaN,1.09,1.09

In [118]:
df.groupby("item_name").total_price.sum()

item_name
6 Pack Soft Drink                         369.93
Barbacoa Bowl                             672.36
Barbacoa Burrito                          894.75
Barbacoa Crispy Tacos                     138.71
Barbacoa Salad Bowl                       106.40
Barbacoa Soft Tacos                       250.46
Bottled Water                             649.18
Bowl                                       74.00
Burrito                                    44.40
Canned Soda                               191.84
Canned Soft Drink                         603.75
Carnitas Bowl                             830.71
Carnitas Burrito                          616.33
Carnitas Crispy Tacos                      95.94
Carnitas Salad                              8.99
Carnitas Salad Bowl                        66.34
Carnitas Soft Tacos                       375.94
Chicken Bowl                             8044.63
Chicken Burrito                          6387.06
Chicken Crispy Tacos                      524.11
Chicken Salad                              81.09
Chicken Salad Bowl                       1506.25
Chicken Soft Tacos                       1199.01
Chips                                     580.34
Chips and Fresh Tomato Salsa             1033.96
Chips and Guacamole                      2475.62
Chips and Mild Fresh Tomato Salsa           3.00
Chips and Roasted Chili Corn Salsa         73.75
Chips and Roasted Chili-Corn Salsa         43.02
Chips and Tomatillo Green Chili Salsa     144.55
Chips and Tomatillo Red Chili Salsa       159.30
Chips and Tomatillo-Green Chili Salsa      88.43
Chips and Tomatillo-Red Chili Salsa        93.21
Crispy Tacos                               14.80
Izze                                       67.80
Nantucket Nectar                          111.87
Salad                                      14.80
Side of Chips                             290.68
Steak Bowl                               2479.81
Steak Burrito                            4236.13
Steak Crispy Tacos                        375.32
Steak Salad                                35.66
Steak Salad Bowl                          391.15
Steak Soft Tacos                          554.55
Veggie Bowl                               901.95
Veggie Burrito                           1002.27
Veggie Crispy Tacos                         8.49
Veggie Salad                               50.94
Veggie Salad Bowl                         182.50
Veggie Soft Tacos                          90.94
Name: total_price, dtype: float64

In [119]:
df.groupby("item_name").quantity.sum().sort_values(ascending=False).head(5)

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [120]:
#Bài 11 — số lượng món khác nhau
df.item_name.nunique()

50

In [121]:
#Bài 12 — món bán nhiều nhất theo tổng quantity
df.groupby("item_name").quantity.sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [122]:
#Bài 13 — giá trung bình mỗi món
df.groupby("item_name").item_price.mean()

item_name
6 Pack Soft Drink                         6.610185
Barbacoa Bowl                            10.187273
Barbacoa Burrito                          9.832418
Barbacoa Crispy Tacos                    10.928182
Barbacoa Salad Bowl                      10.640000
Barbacoa Soft Tacos                      10.018400
Bottled Water                             1.867654
Bowl                                     14.800000
Burrito                                   7.400000
Canned Soda                               1.320577
Canned Soft Drink                         1.457641
Carnitas Bowl                            10.833971
Carnitas Burrito                         10.132712
Carnitas Crispy Tacos                    11.137143
Carnitas Salad                            8.990000
Carnitas Salad Bowl                      11.056667
Carnitas Soft Tacos                       9.398500
Chicken Bowl                             10.113953
Chicken Burrito                          10.082857
Chicken Crispy Tacos                     10.045319
Chicken Salad                             9.010000
Chicken Salad Bowl                       11.170455
Chicken Soft Tacos                        9.635565
Chips                                     2.342844
Chips and Fresh Tomato Salsa              3.285091
Chips and Guacamole                       4.595073
Chips and Mild Fresh Tomato Salsa         3.000000
Chips and Roasted Chili Corn Salsa        3.084091
Chips and Roasted Chili-Corn Salsa        2.390000
Chips and Tomatillo Green Chili Salsa     3.087209
Chips and Tomatillo Red Chili Salsa       3.072917
Chips and Tomatillo-Green Chili Salsa     2.544194
Chips and Tomatillo-Red Chili Salsa       2.987500
Crispy Tacos                              7.400000
Izze                                      3.390000
Nantucket Nectar                          3.641111
Salad                                     7.400000
Side of Chips                             1.840594
Steak Bowl                               10.711801
Steak Burrito                            10.465842
Steak Crispy Tacos                       10.209714
Steak Salad                               8.915000
Steak Salad Bowl                         11.847931
Steak Soft Tacos                          9.746364
Veggie Bowl                              10.211647
Veggie Burrito                            9.839684
Veggie Crispy Tacos                       8.490000
Veggie Salad                              8.490000
Veggie Salad Bowl                        10.138889
Veggie Soft Tacos                        10.565714
Name: item_price, dtype: float64

In [123]:
#Bài 14 — đơn hàng có tổng tiền cao nhất
df.groupby("order_id").total_price.sum()

order_id
1       11.56
2       33.96
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: total_price, Length: 1834, dtype: float64

In [ ]:
#Bài 15 — số món trung bình mỗi đơn
df.groupby("item_name")